### PR TITLE
Add support for STARTTLS to nntpclient

### PR DESCRIPTION
**Pull request by jpneverwas**
Thanks for making this library.

This patch also adds basic support for the [RFC 3977 `CAPABILITIES` command][1], which `STARTTLS` depends on. Here are some highlights:

1. The `Client` object now keeps a reference to the `net.Conn` connection alongside the main `textproto.Conn` one.
2. A convenience entrypoint called `NewTLS` serves as a counterpart to `NEW` for dedicated, non-`STARTTLS` TLS connections.
3. The connection type accepted by `NewConn` is now a concrete `net.Conn` instead of an `io.ReadWriteCloser` interface. This is arguably a breaking change but shouldn't impact anyone.

In another [project][2], I have some e2e-ish tests that indirectly prove a few of this file's facilities.

Thanks again.

P.S. I only just now noticed #8 (from 4 years ago!) and would be happy to rework this based off that if people are interested, since there's already a bit of overlap.

[1]: https://datatracker.ietf.org/doc/html/rfc3977#section-3.3

[2]: https://gitlab.com/jpneverwas/nntp-crier

### CODE REVIEW

**Review by dustin — APPROVED** [review]
This looks pretty great.  Thanks for putting time into this.  I've not had much of a use for NNTP (or go for that matter) in a bit, so I'm quite pleased to see some activity.

Would you be interested in having write access to the repo to finish up whatever else you might need here?

**Comment by jpneverwas** [comment]
Dustin Sallings ***@***.***> writes:

> This looks pretty great. Thanks for putting time into this. I've not
> had much of a use for NNTP (or go for that matter) in a bit, so I'm
> quite pleased to see some activity.

Right on!

> Would you be interested in having write access to the repo to finish
> up whatever else you might need here?

That's very generous. I hadn't really given much thought to proposing
anything beyond these changes. So anything immediately forthcoming from
my end would most likely be limited to righting embarrassing wrongs
introduced by this patch. Appreciate the offer, though, truly.

> This function and the next (and others) seem nearly identical other
> than a string input and the code to search for. A helper might be good
> here.

Thanks, this should have bothered me too. I've factored out the common
request-response business into a poorly named helper.

Some other changes:

1. Recognize tabs as valid token delimiters in capability lines.

2. Normalize case before comparing capability tokens.

3. Use more precise terminology in comments, e.g., "label" for initial
   tokens in CAPABILITIES response lines.

BTW, I'd be happy to squash this (and any remaining tweaks) down into
the first.

**Comment by dustin** [comment]
Sorry it took me a while here.  I'm pretty slow at the go stuff these days. :)

**Comment by jpneverwas** [comment]
Dustin Sallings ***@***.***> writes:

> Sorry it took me a while here. I'm pretty slow at the go stuff these days. :)

Not at all. I'm pretty slow in general. Thanks again for making this!

**Pull request merged**
